Update python-pipeline.yml

diff --git a/.github/workflows/python-pipeline.yml b/.github/workflows/python-pipeline.yml
--- a/.github/workflows/python-pipeline.yml
+++ b/.github/workflows/python-pipeline.yml
@@ -235,157 +235,163 @@ jobs:
         with:
           name: sustainos-package
           path: dist/*
-          
+
       - name: Download Artifact
         uses: actions/download-artifact@v4
         with:
-          name: sustainos-package  # Name of the artifact from the previous job
-          path: artifact-output   # Directory where the artifact will be downloaded
+          name: sustainos-package
+          path: artifact-output  # Directory where the artifact will be downloaded
 
-      - name: Prepare Extraction Directory
-        run: |
-          mkdir -p extracted
-      
-      - name: Unzip or Extract Artifact
-        run: |
-          if ls artifact-output/*.zip >/dev/null 2>&1; then
-            echo "Zip file found, extracting..."
-            unzip artifact-output/*.zip -d extracted
-          elif ls artifact-output/*.tar.gz >/dev/null 2>&1; then
-            echo "Tarball found, extracting..."
-            tar -xzvf artifact-output/*.tar.gz -C extracted
-          else
-            echo "No valid artifact (zip or tar.gz) found in artifact-output directory."
-            exit 1
-          fi
-      
-      - name: Verify Artifact Structure
-        run: |
-          echo "Contents of the extracted directory:"
-          ls -R extracted
-      
-      - name: Download Artifact
-        uses: actions/download-artifact@v4
+      - name: Upload Artifact to EC2
+        uses: appleboy/ssh-action@v0.1.2
         with:
-          name: sustainos-package  # Name of the artifact from the previous job
-          path: artifact-output   # Directory where the artifact will be downloaded
+          host: ${{ secrets.EC2_PUBLIC_IP }}
+          username: ec2-user
+          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
+          script: |
+            mkdir -p /home/ec2-user/artifact
+            scp -r artifact-output/* ec2-user@${{ secrets.EC2_PUBLIC_IP }}:/home/ec2-user/artifact/   
+          
+      # - name: Download Artifact
+      #   uses: actions/download-artifact@v4
+      #   with:
+      #     name: sustainos-package  # Name of the artifact from the previous job
+      #     path: artifact-output   # Directory where the artifact will be downloaded
 
-      - name: Build Docker Image with Artifact
-        if: env.should_deploy == 'true'
-        run: |
-          docker build --build-arg ARTIFACT_PATH=artifact-output -t sustainos-image .
-
+      # - name: Prepare Extraction Directory
+      #   run: |
+      #     mkdir -p extracted
       
-      - name: List Extracted Files
-        run: |
-          echo "Listing contents of the extracted directory:"
-          ls -R extracted
-
+      # - name: Unzip or Extract Artifact
+      #   run: |
+      #     if ls artifact-output/*.zip >/dev/null 2>&1; then
+      #       echo "Zip file found, extracting..."
+      #       unzip artifact-output/*.zip -d extracted
+      #     elif ls artifact-output/*.tar.gz >/dev/null 2>&1; then
+      #       echo "Tarball found, extracting..."
+      #       tar -xzvf artifact-output/*.tar.gz -C extracted
+      #     else
+      #       echo "No valid artifact (zip or tar.gz) found in artifact-output directory."
+      #       exit 1
+      #     fi
       
-      # Step to Build Docker Images
-      - name: Build Docker Image with Artifact
-        if: env.should_deploy == 'true'
-        run: |
-          docker build --build-arg ARTIFACT_PATH=extracted -t sustainos-image .
-
+      # - name: Verify Artifact Structure
+      #   run: |
+      #     echo "Contents of the extracted directory:"
+      #     ls -R extracted
       
-      - name: Set up Docker image for deployment
-        if: env.should_deploy == 'true'
-        run: |
-          # Retrieve the highest existing version tag (v1, v2, ...) and increment it
-          EXISTING_TAG=$(aws ecr describe-images \
-            --repository-name ${{ secrets.ECR_REPO_NAME }} \
-            --query 'imageDetails[].imageTags[]' \
-            --output text | grep -o 'v[0-9]*' | sed 's/v//' | sort -n | tail -1 2>/dev/null || echo 0)
-          
-          # Increment the version for the new tag
-          NEW_VERSION_TAG=v$((EXISTING_TAG + 1))
-          
-          # Build the Docker image with the version tag and latest tag
-          docker build -t ${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG} -t ${{ secrets.ECR_REPO_NAME }}:latest .
-          
-          # Tag the image for ECR with both the version tag and latest tag
-          docker tag ${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG}
-          docker tag ${{ secrets.ECR_REPO_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
-          
-          # Authenticate Docker to AWS ECR
-          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
-          
-          # Push the image to ECR with both tags
-          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG}
-          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
 
       
-      - name: SSH to EC2 and deploy Docker container
-        if: env.should_deploy == 'true'
-        run: |
-          # Create a temporary SSH key file
-          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
-          chmod 600 ec2_key.pem
+      # - name: List Extracted Files
+      #   run: |
+      #     echo "Listing contents of the extracted directory:"
+      #     ls -R extracted
+
       
-          # Add EC2's SSH host key to known_hosts to avoid host key verification issues
-          mkdir -p ~/.ssh
-          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
+      # # Step to Build Docker Images
+      # - name: Build Docker Image with Artifact
+      #   if: env.should_deploy == 'true'
+      #   run: |
+      #     docker build --build-arg ARTIFACT_PATH=extracted -t sustainos-image .
+
       
-          # SSH to the EC2 instance and run commands
-          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
-            # Install Docker if it's not installed
-            if ! command -v docker &> /dev/null
-            then
-              echo "Docker not found, installing..."
-              sudo yum update -y
-              sudo yum install -y docker
-              sudo service docker start
-              sudo systemctl enable docker
-            else
-              echo "Docker is already installed"
-            fi
+      # - name: Set up Docker image for deployment
+      #   if: env.should_deploy == 'true'
+      #   run: |
+      #     # Retrieve the highest existing version tag (v1, v2, ...) and increment it
+      #     EXISTING_TAG=$(aws ecr describe-images \
+      #       --repository-name ${{ secrets.ECR_REPO_NAME }} \
+      #       --query 'imageDetails[].imageTags[]' \
+      #       --output text | grep -o 'v[0-9]*' | sed 's/v//' | sort -n | tail -1 2>/dev/null || echo 0)
+          
+      #     # Increment the version for the new tag
+      #     NEW_VERSION_TAG=v$((EXISTING_TAG + 1))
+          
+      #     # Build the Docker image with the version tag and latest tag
+      #     docker build -t ${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG} -t ${{ secrets.ECR_REPO_NAME }}:latest .
+          
+      #     # Tag the image for ECR with both the version tag and latest tag
+      #     docker tag ${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG}
+      #     docker tag ${{ secrets.ECR_REPO_NAME }}:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
+          
+      #     # Authenticate Docker to AWS ECR
+      #     aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
+          
+      #     # Push the image to ECR with both tags
+      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:${NEW_VERSION_TAG}
+      #     docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
+
       
-            # Add ec2-user to Docker group to allow non-root access to Docker
-            sudo usermod -aG docker ec2-user
-            newgrp docker
+      # - name: SSH to EC2 and deploy Docker container
+      #   if: env.should_deploy == 'true'
+      #   run: |
+      #     # Create a temporary SSH key file
+      #     echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
+      #     chmod 600 ec2_key.pem
       
-            # Authenticate Docker to AWS ECR
-            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
+      #     # Add EC2's SSH host key to known_hosts to avoid host key verification issues
+      #     mkdir -p ~/.ssh
+      #     ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
       
-            # Remove existing container with the same name
-            if [ "$(docker ps -aq -f name=my-app-container)" ]; then
-              echo "Removing existing container 'my-app-container'..."
-              docker stop my-app-container
-              docker rm my-app-container
-            fi
+      #     # SSH to the EC2 instance and run commands
+      #     ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+      #       # Install Docker if it's not installed
+      #       if ! command -v docker &> /dev/null
+      #       then
+      #         echo "Docker not found, installing..."
+      #         sudo yum update -y
+      #         sudo yum install -y docker
+      #         sudo service docker start
+      #         sudo systemctl enable docker
+      #       else
+      #         echo "Docker is already installed"
+      #       fi
       
-            # Pull the Docker image from ECR
-            echo "Pulling the latest Docker image..."
-            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
+      #       # Add ec2-user to Docker group to allow non-root access to Docker
+      #       sudo usermod -aG docker ec2-user
+      #       newgrp docker
       
-            # Run the container
-            echo "Deploying the new container..."
-            docker run -d -p 9000:9000 --name my-app-container \
-              -e DATABASE_NAME="${{ secrets.DATABASE_NAME }}" \
-              -e DATABASE_USER="${{ secrets.DATABASE_USER }}" \
-              -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
-              -e DATABASE_HOST="${{ secrets.DATABASE_HOST }}" \
-              -e DATABASE_PORT="${{ secrets.DATABASE_PORT }}" \
-              -e EMAIL_BACKEND="${{ secrets.EMAIL_BACKEND }}" \
-              -e CENTRALIZED_HOSTED_URL="${{ secrets.CENTRALIZED_HOSTED_URL }}" \
-              -e EMAIL_HOST_USER="${{ secrets.EMAIL_HOST_USER }}" \
-              -e EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}" \
-              -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
-              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
+      #       # Authenticate Docker to AWS ECR
+      #       aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
       
-            # Verify the container is running
-            if ! docker ps -q -f name=my-app-container; then
-              echo "Failed to start the container 'my-app-container'. Exiting."
-              exit 1
-            fi
-            echo "Container 'my-app-container' is running successfully."
-          EOF
+      #       # Remove existing container with the same name
+      #       if [ "$(docker ps -aq -f name=my-app-container)" ]; then
+      #         echo "Removing existing container 'my-app-container'..."
+      #         docker stop my-app-container
+      #         docker rm my-app-container
+      #       fi
       
-      - name: List Docker Images on EC2
-        run: |
-          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker images"
+      #       # Pull the Docker image from ECR
+      #       echo "Pulling the latest Docker image..."
+      #       docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
       
-      - name: List Running Containers on EC2
-        run: |
-          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker ps -a"
+      #       # Run the container
+      #       echo "Deploying the new container..."
+      #       docker run -d -p 9000:9000 --name my-app-container \
+      #         -e DATABASE_NAME="${{ secrets.DATABASE_NAME }}" \
+      #         -e DATABASE_USER="${{ secrets.DATABASE_USER }}" \
+      #         -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
+      #         -e DATABASE_HOST="${{ secrets.DATABASE_HOST }}" \
+      #         -e DATABASE_PORT="${{ secrets.DATABASE_PORT }}" \
+      #         -e EMAIL_BACKEND="${{ secrets.EMAIL_BACKEND }}" \
+      #         -e CENTRALIZED_HOSTED_URL="${{ secrets.CENTRALIZED_HOSTED_URL }}" \
+      #         -e EMAIL_HOST_USER="${{ secrets.EMAIL_HOST_USER }}" \
+      #         -e EMAIL_HOST_PASSWORD="${{ secrets.EMAIL_HOST_PASSWORD }}" \
+      #         -e SECRET_KEY="${{ secrets.SECRET_KEY }}" \
+      #         ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
+      
+      #       # Verify the container is running
+      #       if ! docker ps -q -f name=my-app-container; then
+      #         echo "Failed to start the container 'my-app-container'. Exiting."
+      #         exit 1
+      #       fi
+      #       echo "Container 'my-app-container' is running successfully."
+      #     EOF
+      
+      # - name: List Docker Images on EC2
+      #   run: |
+      #     ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker images"
+      
+      # - name: List Running Containers on EC2
+      #   run: |
+      #     ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker ps -a"
