Update python-pipeline.yml

diff --git a/.github/workflows/python-pipeline.yml b/.github/workflows/python-pipeline.yml
--- a/.github/workflows/python-pipeline.yml
+++ b/.github/workflows/python-pipeline.yml
@@ -295,6 +295,18 @@ jobs:
       
           # SSH to the EC2 instance and run commands
           ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+            # Install Docker if it's not installed
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo yum update -y
+              sudo yum install -y docker
+              sudo service docker start
+              sudo systemctl enable docker
+            else
+              echo "Docker is already installed"
+            fi
+      
             # Authenticate Docker to AWS ECR
             aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
       
@@ -320,6 +332,7 @@ jobs:
           rm -f ec2_key.pem
 
 
+      
       - name: List Docker Images on EC2
         run: |
           ssh -i ${{ secrets.EC2_SSH_KEY }} ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker images"
