Update python-pipeline.yml

diff --git a/.github/workflows/python-pipeline.yml b/.github/workflows/python-pipeline.yml
--- a/.github/workflows/python-pipeline.yml
+++ b/.github/workflows/python-pipeline.yml
@@ -36,7 +36,7 @@ jobs:
         uses: actions/checkout@v3
         with:
           repository: ${{ env.REPO_NAME }}
-          ref: 'feature/demo-testing'  # Checkout the correct branch
+          ref: 'feature/demo-testing'
 
   unit_tests:
     name: Run Unit Tests
@@ -58,9 +58,16 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
 
+      - name: Check if tests directory exists
+        run: |
+          if [ ! -d "tests" ]; then
+            echo "Tests directory not found!"
+            exit 1
+          fi
+
       - name: Run Unit Tests
         env:
-          PYTHONPATH: ./src
+          PYTHONPATH: ./tests
         run: python -m unittest discover tests
 
   pytest_tests:
