Update python-pipeline.yml

diff --git a/.github/workflows/python-pipeline.yml b/.github/workflows/python-pipeline.yml
--- a/.github/workflows/python-pipeline.yml
+++ b/.github/workflows/python-pipeline.yml
@@ -140,10 +140,10 @@ jobs:
         run: |
           git fetch origin main
           if git diff --exit-code HEAD origin/main -- . > /dev/null; then
-            echo "Changes detected. Proceeding with version bump and deployment."
+            echo "No changes detected. Skipping version bump and deployment."
             echo "should_deploy=true" >> $GITHUB_ENV
           else
-            echo "No changes detected. Skipping version bump and deployment."
+            echo "Changes detected. Proceeding with version bump and deployment."
             echo "should_deploy=false" >> $GITHUB_ENV
           fi
 
@@ -216,11 +216,16 @@ jobs:
 
       - name: Deploy to EC2
         run: |
-          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
+          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ec2-user@*** << 'EOF'
             cd /home/ec2-user/dt-python-app1-testing-repo/
-            python3 -m venv venv
-            source venv/bin/activate
-            sudo python3 -m pip install --upgrade pip
-            sudo python3 -m pip install -r requirements.txt
+            if [ -f "requirements.txt" ]; then
+              python3 -m venv venv
+              source venv/bin/activate
+              sudo python3 -m pip install --upgrade pip
+              sudo python3 -m pip install -r requirements.txt
+            else
+              echo "requirements.txt not found!"
+              exit 1
+            fi
             sudo systemctl restart my-python-app.service
           EOF
