Update python-pipeline.yml

diff --git a/.github/workflows/python-pipeline.yml b/.github/workflows/python-pipeline.yml
--- a/.github/workflows/python-pipeline.yml
+++ b/.github/workflows/python-pipeline.yml
@@ -248,6 +248,14 @@ jobs:
               --query "versions | sort_by(@, &version) | [-1].version" \
               --output text)
       
+            # Check if LATEST_VERSION is not empty
+            if [ -z "$LATEST_VERSION" ]; then
+              echo "Error: No version found for package 'calculator'."
+              exit 1
+            fi
+      
+            echo "Latest version of calculator: $LATEST_VERSION"
+      
             # Download the latest version of the package asset
             aws codeartifact get-package-version-asset \
               --domain aeiforo \
@@ -262,7 +270,7 @@ jobs:
             # Verify the downloaded package
             ls -lh output.zip
           EOF
-      
+
       - name: Unzip the Package Asset
         run: |
           ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
