Update python-pipeline.yml

diff --git a/.github/workflows/python-pipeline.yml b/.github/workflows/python-pipeline.yml
--- a/.github/workflows/python-pipeline.yml
+++ b/.github/workflows/python-pipeline.yml
@@ -182,6 +182,12 @@ jobs:
         run: |
           python setup.py sdist bdist_wheel
 
+      - name: Debug Build Output
+        if: env.should_deploy == 'true'
+        run: |
+          echo "Checking the dist directory..."
+          ls -l dist/
+
       - name: Configure AWS Credentials
         if: env.should_deploy == 'true'
         uses: aws-actions/configure-aws-credentials@v2
@@ -210,11 +216,22 @@ jobs:
         with:
           name: calculator-package
           path: dist/*
-          
+
+      - name: Validate File Before S3 Upload
+        if: env.should_deploy == 'true'
+        run: |
+          if [ ! -f "dist/calculator-latest.tar.gz" ]; then
+            echo "Error: dist/calculator-latest.tar.gz does not exist."
+            exit 1
+          else
+            echo "File dist/calculator-latest.tar.gz exists. Proceeding to upload."
+          fi
+
       - name: Upload Latest Version to S3
         if: env.should_deploy == 'true'
         run: |
           aws s3 cp dist/calculator-latest.tar.gz s3://code-artifact-latest-version
+
           
   deploy_to_ec2:
       name: Deploy to EC2
