Update python-pipeline.yml

diff --git a/.github/workflows/python-pipeline.yml b/.github/workflows/python-pipeline.yml
--- a/.github/workflows/python-pipeline.yml
+++ b/.github/workflows/python-pipeline.yml
@@ -292,7 +292,9 @@ jobs:
           ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
       
           # SSH to the EC2 instance and run commands
-          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << EOF
+            CONTAINER_NAME="${{ secrets.CONTAINER_NAME }}"
+      
             # Install Docker if it's not installed
             if ! command -v docker &> /dev/null
             then
@@ -313,10 +315,10 @@ jobs:
             aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
       
             # Remove existing container with the same name
-            if [ "$(docker ps -aq -f name=my-app-container)" ]; then
-              echo "Removing existing container 'my-app-container'..."
-              docker stop my-app-container
-              docker rm my-app-container
+            if [ "\$(docker ps -aq -f name=\$CONTAINER_NAME)" ]; then
+              echo "Removing existing container '\$CONTAINER_NAME'..."
+              docker stop \$CONTAINER_NAME
+              docker rm \$CONTAINER_NAME
             fi
       
             # Pull the Docker image from ECR
@@ -325,7 +327,7 @@ jobs:
       
             # Run the container
             echo "Deploying the new container..."
-            docker run -d -p 9000:9000 --name my-app-container \
+            docker run -d -p 9000:9000 --name \$CONTAINER_NAME \
               -e DATABASE_NAME="${{ secrets.DATABASE_NAME }}" \
               -e DATABASE_USER="${{ secrets.DATABASE_USER }}" \
               -e DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}" \
@@ -339,11 +341,11 @@ jobs:
               ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
       
             # Verify the container is running
-            if ! docker ps -q -f name=my-app-container; then
-              echo "Failed to start the container 'my-app-container'. Exiting."
+            if ! docker ps -q -f name=\$CONTAINER_NAME; then
+              echo "Failed to start the container '\$CONTAINER_NAME'. Exiting."
               exit 1
             fi
-            echo "Container 'my-app-container' is running successfully."
+            echo "Container '\$CONTAINER_NAME' is running successfully."
           EOF
       
       - name: List Docker Images on EC2
