Update react-pipeline.yml

diff --git a/.github/workflows/react-pipeline.yml b/.github/workflows/react-pipeline.yml
--- a/.github/workflows/react-pipeline.yml
+++ b/.github/workflows/react-pipeline.yml
@@ -187,181 +187,149 @@ jobs:
           name: react-app-build
           path: build/
           
-  download_and_extract_artifact:
-    name: Download and Extract Artifact
+
+  docker:
+    name: Docker Build and Deploy
     runs-on: ubuntu-latest
-    needs: build_and_publish_artifact
-    if: env.should_deploy == 'true'
+    needs:  build_and_publish_artifact
   
     steps:
-      - name: Download Artifact
-        uses: actions/download-artifact@v3
+      - name: Checkout Code
+        uses: actions/checkout@v3
+  
+      - name: Set up AWS CLI
+        uses: aws-actions/configure-aws-credentials@v2
         with:
-          name: react-app-build
-          path: ./artifact
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ inputs.aws-region }}
   
-      - name: Debug Artifact Directory
-        run: ls -la ./artifact
+      - name: Get Version from version.txt
+        id: version
+        run: echo "version=$(cat version.txt)" >> $GITHUB_ENV
   
-      - name: Extract Artifact
+      - name: Retrieve Existing Version from ECR
+        id: ecr-version
         run: |
-          ARTIFACT_FILE=$(find ./artifact -name '*.tgz')
-          if [ -z "$ARTIFACT_FILE" ]; then
-            echo "No .tgz file found in artifact directory!"
-            exit 1
+          EXISTING_TAG=$(aws ecr describe-images \
+            --repository-name ${{ inputs.ecr-repo-name }} \
+            --query 'imageDetails[].imageTags[]' \
+            --output text | grep -o 'v[0-9]*' | sed 's/v//' | sort -n | tail -1 2>/dev/null || echo 0)
+          echo "EXISTING_TAG=$EXISTING_TAG" >> $GITHUB_ENV
+  
+      - name: Increment Version
+        id: increment-version
+        run: |
+          NEW_VERSION_TAG=v$((EXISTING_TAG + 1))
+          echo "NEW_VERSION_TAG=$NEW_VERSION_TAG" >> $GITHUB_ENV
+          echo "NEW_VERSION_TAG=$NEW_VERSION_TAG"
+  
+      - name: Prepare Build Context
+        run: |
+          echo "Navigating to project directory:"
+          cd /home/runner/work/dt-frontend-repo/dt-frontend-repo
+          echo "Current directory:"
+          pwd
+          echo "Ensuring 'extracted-package' exists:"
+          if [ ! -d "extracted-package" ]; then
+            echo "'extracted-package' directory is missing! Creating it now..."
+            mkdir extracted-package
+          else
+            echo "'extracted-package' directory exists."
           fi
-          mkdir -p extracted-artifact
-          tar -xzf "$ARTIFACT_FILE" -C extracted-artifact
-  
-      - name: Debug Extracted Directory
-        run: ls -la extracted-artifact
-  
-    
-
-  # docker:
-  #   name: Docker Build and Deploy
-  #   runs-on: ubuntu-latest
-  #   needs:  build_and_publish_artifact
-  
-  #   steps:
-  #     - name: Checkout Code
-  #       uses: actions/checkout@v3
-  
-  #     - name: Set up AWS CLI
-  #       uses: aws-actions/configure-aws-credentials@v2
-  #       with:
-  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  #         aws-region: ${{ inputs.aws-region }}
-  
-  #     - name: Get Version from version.txt
-  #       id: version
-  #       run: echo "version=$(cat version.txt)" >> $GITHUB_ENV
-  
-  #     - name: Retrieve Existing Version from ECR
-  #       id: ecr-version
-  #       run: |
-  #         EXISTING_TAG=$(aws ecr describe-images \
-  #           --repository-name ${{ inputs.ecr-repo-name }} \
-  #           --query 'imageDetails[].imageTags[]' \
-  #           --output text | grep -o 'v[0-9]*' | sed 's/v//' | sort -n | tail -1 2>/dev/null || echo 0)
-  #         echo "EXISTING_TAG=$EXISTING_TAG" >> $GITHUB_ENV
-  
-  #     - name: Increment Version
-  #       id: increment-version
-  #       run: |
-  #         NEW_VERSION_TAG=v$((EXISTING_TAG + 1))
-  #         echo "NEW_VERSION_TAG=$NEW_VERSION_TAG" >> $GITHUB_ENV
-  #         echo "NEW_VERSION_TAG=$NEW_VERSION_TAG"
-  
-  #     - name: Prepare Build Context
-  #       run: |
-  #         echo "Navigating to project directory..."
-  #         cd /home/runner/work/dt-frontend-repo/dt-frontend-repo
-  #         echo "Current directory:"
-  #         pwd
+          echo "Copying everything to 'extracted-package' directory, excluding itself:"
+          find . -mindepth 1 -maxdepth 1 ! -name 'extracted-package' -exec cp -r {} extracted-package/ \;
+          echo "Listing files in the project directory:"
+          ls -la
+          echo "Verifying extracted-package contents:"
+          ls -la extracted-package
       
-  #         echo "Ensuring 'extracted-package' directory is empty..."
-  #         if [ -d "extracted-package" ]; then
-  #           echo "'extracted-package' directory exists. Clearing contents..."
-  #           rm -rf extracted-package/*
-  #         else
-  #           echo "'extracted-package' directory does not exist. Creating it..."
-  #           mkdir extracted-package
-  #         fi
-      
-  #         echo "Copying everything to 'extracted-package' directory, excluding itself..."
-  #         find . -mindepth 1 -maxdepth 1 ! -name 'extracted-package' -exec cp -r {} extracted-package/ \;
-      
-  #         echo "Listing files in the project directory..."
-  #         ls -la
-      
-  #         echo "Verifying contents of 'extracted-package'..."
-  #         ls -la extracted-package
-      
-  #     - name: Build Docker Image
-  #       run: |
-  #         echo "Building Docker image using 'extracted-package' as context..."
-  #         docker build --build-arg ARTIFACT_VERSION=${{ env.NEW_VERSION_TAG }} \
-  #         -t ${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }} \
-  #         -t ${{ inputs.ecr-repo-name }}:latest \
-  #         ./extracted-package
+
+      - name: Build Docker Image
+        run: |
+          echo "Navigating to project directory:"
+          cd /home/runner/work/dt-frontend-repo/dt-frontend-repo
+          echo "Building Docker image..."
+          docker build --build-arg ARTIFACT_VERSION=${{ env.NEW_VERSION_TAG }} \
+          -t ${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }} \
+          -t ${{ inputs.ecr-repo-name }}:latest \
+          .
 
   
-  #     - name: Authenticate Docker with ECR
-  #       run: |
-  #         aws ecr get-login-password --region ${{ inputs.aws-region }} | \
-  #         docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
+      - name: Authenticate Docker with ECR
+        run: |
+          aws ecr get-login-password --region ${{ inputs.aws-region }} | \
+          docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com
   
-  #     - name: Tag and Push Docker Images
-  #       run: |
-  #         docker tag ${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }} \
-  #           ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }}
-  #         docker tag ${{ inputs.ecr-repo-name }}:latest \
-  #           ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:latest
-  #         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }}
-  #         docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:latest
+      - name: Tag and Push Docker Images
+        run: |
+          docker tag ${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }} \
+            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }}
+          docker tag ${{ inputs.ecr-repo-name }}:latest \
+            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:latest
+          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:${{ env.NEW_VERSION_TAG }}
+          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ inputs.aws-region }}.amazonaws.com/${{ inputs.ecr-repo-name }}:latest
 
-  #     - name: SSH to EC2 and deploy Docker container
-  #       run: |
-  #         # Create a temporary SSH key file
-  #         echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
-  #         chmod 600 ec2_key.pem
+      - name: SSH to EC2 and deploy Docker container
+        run: |
+          # Create a temporary SSH key file
+          echo "${{ secrets.EC2_SSH_KEY }}" > ec2_key.pem
+          chmod 600 ec2_key.pem
 
-  #         # Add EC2's SSH host key to known_hosts to avoid host key verification issues
-  #         mkdir -p ~/.ssh
-  #         ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
+          # Add EC2's SSH host key to known_hosts to avoid host key verification issues
+          mkdir -p ~/.ssh
+          ssh-keyscan -H ${{ secrets.EC2_PUBLIC_IP }} >> ~/.ssh/known_hosts
 
-  #         # SSH to the EC2 instance and run commands
-  #         ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
-  #           # Install Docker if it's not installed
-  #           if ! command -v docker &> /dev/null
-  #           then
-  #             echo "Docker not found, installing..."
-  #             sudo yum update -y docker 
-  #             sudo yum install -y docker
-  #             sudo service docker start
-  #             sudo systemctl enable docker
-  #           else
-  #             echo "Docker is already installed"
-  #           fi
+          # SSH to the EC2 instance and run commands
+          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
+            # Install Docker if it's not installed
+            if ! command -v docker &> /dev/null
+            then
+              echo "Docker not found, installing..."
+              sudo yum update -y docker 
+              sudo yum install -y docker
+              sudo service docker start
+              sudo systemctl enable docker
+            else
+              echo "Docker is already installed"
+            fi
 
-  #           # Add ec2-user to Docker group to allow non-root access to Docker
-  #           sudo usermod -aG docker ec2-user
-  #           newgrp docker
+            # Add ec2-user to Docker group to allow non-root access to Docker
+            sudo usermod -aG docker ec2-user
+            newgrp docker
 
-  #           # Authenticate Docker to AWS ECR
-  #           aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
+            # Authenticate Docker to AWS ECR
+            aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com
 
-  #           # Remove existing container with the same name (for React app)
-  #           if [ "$(docker ps -aq -f name=react-container)" ]; then
-  #             echo "Removing existing container 'react-container'..."
-  #             docker stop react-container
-  #             docker rm react-container
-  #           fi
+            # Remove existing container with the same name (for React app)
+            if [ "$(docker ps -aq -f name=react-container)" ]; then
+              echo "Removing existing container 'react-container'..."
+              docker stop react-container
+              docker rm react-container
+            fi
 
-  #           # Pull the latest Docker image from ECR
-  #           echo "Pulling the latest Docker image..."
-  #           docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
+            # Pull the latest Docker image from ECR
+            echo "Pulling the latest Docker image..."
+            docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
 
-  #           # Run the new container with the name 'react-container'
-  #           echo "Deploying the new container 'react-container'..."
-  #           - name: Run Docker Container
-  #             docker run -d -p 8001:80 --name react-container ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
+            # Run the new container with the name 'react-container'
+            echo "Deploying the new container 'react-container'..."
+            - name: Run Docker Container
+              docker run -d -p 8001:80 --name react-container ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.us-east-1.amazonaws.com/${{ secrets.ECR_REPO_NAME }}:latest
 
 
-  #           # Verify the container is running
-  #           if ! docker ps -q -f name=react-container; then
-  #             echo "Failed to start the container 'react-container'. Exiting."
-  #             exit 1
-  #           fi
-  #           echo "Container 'react-container' is running successfully."
-  #         EOF
+            # Verify the container is running
+            if ! docker ps -q -f name=react-container; then
+              echo "Failed to start the container 'react-container'. Exiting."
+              exit 1
+            fi
+            echo "Container 'react-container' is running successfully."
+          EOF
 
-  #     - name: List Docker Images on EC2
-  #       run: |
-  #         ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker images"
+      - name: List Docker Images on EC2
+        run: |
+          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker images"
 
-  #     - name: List Running Containers on EC2
-  #       run: |
-  #         ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker ps -a"
+      - name: List Running Containers on EC2
+        run: |
+          ssh -i ec2_key.pem ec2-user@${{ secrets.EC2_PUBLIC_IP }} "sudo docker ps -a"
